from django.db import models
from django.utils.translation import gettext_lazy as _


class Regions(models.IntegerChoices):
    """Region Choices"""
    QORAQALPOGISTON = 1, _('Qoraqalpog‘iston Respublikasi')
    ANDIJON = 2, _('Andijon viloyati')
    BUXORO = 3, _('Buxoro viloyati')
    JIZZAX = 4, _('Jizzax viloyati')
    QASHQADARYO = 5, _('Qashqadaryo viloyati')
    NAVOIY = 6, _('Navoiy viloyati')
    NAMANGAN = 7, _('Namangan viloyati')
    SAMARQAND = 8, _('Samarqand viloyati')
    SURXANDARYO = 9, _('Surxandaryo viloyati')
    SIRDARYO = 10, _('Sirdaryo viloyati')
    TOSHKENT = 11, _('Toshkent viloyati')
    FARGONA = 12, _('Farg‘ona viloyati')
    XORAZM = 13, _('Xorazm viloyati')
    TOSHKENT_SHAHRI = 14, _('Toshkent shahri')


class District(models.TextChoices):
    """District Choices"""
    # QORAQALPOGISTON
    AMUDARYO = '1X1', _('Amudaryo tumani')
    BERUNIY = '1X2', _('Beruniy tumani')
    KEGAYLI = '1X3', _('Kegayli tumani')
    QONLIKOL = '1X4', _('Qonliko‘l tumani')
    QORAOZAK = '1X5', _('Qorao‘zak tumani')
    QONGIROT = '1X6', _('Qo‘ng‘irot tumani')
    MOYNOQ = '1X7', _('Mo‘ynoq tumani')
    NUKUS = '1X8', _('Nukus tumani')
    NUKUS_SHAHRI = '1X9', _('Nukus shahri')
    TAXTAKOPIR = '1X10', _('Taxtako‘pir tumani')
    TORTKOL = '1X11', _('To‘rtko‘l tumani')
    XOJAYLI = '1X12', _('Xo‘jayli tumani')
    CHIMBOY = '1X13', _('Chimboy tumani')
    SHUMANAY = '1X14', _('Shumanay tumani')
    ELLIKQALA = '1X15', _('Ellikqal‘a tumani')
    TAXIATOSH = '1X16', _('Taxiatosh shahri')
    BOZATOV = '1X17', _('Bo‘zatov tumani')

    # ANDIJON
    ANDIJON_SHAHRI = '2X1', _('Andijon shahri')
    ANDIJON = '2X2', _('Andijon tumani')
    ASAKA = '2X3', _('Asaka tumani')
    BALIQCHI = '2X4', _('Baliqchi tumani')
    BULOQBOSHI = '2X5', _('Buloqboshi tumani')
    BOZ = '2X6', _('Bo‘z tumani')
    JALAQUDUQ = '2X7', _('Jalaquduq tumani')
    IZBOSGAN = '2X8', _('Izbosgan tumani')
    QORASUV = '2X9', _('Qorasuv shahri')
    QORGONTEPA = '2X10', _('Qo‘rg‘ontepa tumani')
    MARHAMAT = '2X11', _('Marhamat tumani')
    OLTINKOL = '2X12', _('Oltinko‘l tumani')
    PAXTAOBOD = '2X13', _('Paxtaobod tumani')
    ULUGNOR = '2X14', _('Ulug‘nor tumani')
    XONABOD = '2X15', _('Xonabod tumani')
    XOJAOBOD = '2X16', _('Xo‘jaobod tumani')
    SHAHRIXON = '2X17', _('Shahrixon tumani')
    ASAKA = '2X18', _('Asaka shahri')

    # BUXORO
    BUXORO_SHAHRI = '3X1', _('Buxoro shahri')
    BUXORO = '3X2', _('Buxoro tumani')
    VOBKENT = '3X3', _('Vobkent tumani')
    GIJDUVON = '3X4', _('G‘ijduvon tumani')
    JONDOR = '3X5', _('Jondor tumani')
    KOGON = '3X6', _('Kogon tumani')
    KOGON_SHAHRI = '3X7', _('Kogon shahri')
    QORAKOL = '3X8', _('Qorako‘l tumani')
    QOROVULBOZOR = '3X9', _('Qorovulbozor tumani')
    OLOT = '3X10', _('Olot tumani')
    PESHKU = '3X11', _('Peshku tumani')
    ROMITAN = '3X12', _('Romitan tumani')
    SHOFIRKON = '3X13', _('Shofirkon tumani')

    # JIZZAX
    ARNASOY = '4X1', _('Arnasoy tumani')
    BAXMAL = '4X2', _('Baxmal tumani')
    GALLAOROL = '4X3', _('G‘allaorol tumani')
    DOSTLIK = '4X4', _('Do‘stlik tumani')
    RASHIDOV = '4X5', _('Sh.Rashidov tumani')
    JIZZAX = '4X6', _('Jizzax shahri')
    ZARBDOR = '4X7', _('Zarbdor tumani')
    ZAFAROBOD = '4X8', _('Zafarobod tumani')
    ZOMIN = '4X9', _('Zomin tumani')
    MIRZACHOL = '4X10', _('Mirzacho‘l tumani')
    PAXTAKOR = '4X11', _('Paxtakor tumani')
    FORISH = '4X12', _('Forish tumani')
    YANGIOBOD = '4X13', _('Yangiobod tumani')

    #QASHQADARYO
    GUZOR = '5X1', _('G‘uzor tumani')
    DEHQONOBOD = '5X2', _('Dehqonobod tumani')
    QAMASHI = '5X3', _('Qamashi tumani')
    QARSHI = '5X4', _('Qarshi tumani')
    QARSHI_SHAHRI = '5X5', _('Qarshi shahri')
    KASBI = '5X6', _('Kasbi tumani')
    KITOB = '5X7', _('Kitob tumani')
    KOSON = '5X8', _('Koson tumani')
    MIRISHKOR = '5X9', _('Mirishkor tumani')
    MUBORAK = '5X10', _('Muborak tumani')
    NISHON = '5X11', _('Nishon tumani')
    CHIROQCHI = '5X12', _('Chiroqchi tumani')
    SHAHRISABZ = '5X13', _('Shahrisabz tumani')
    YAKKABOG = '5X14', _('Yakkabog‘ tumani')
    SHAHRISABZ_SHAHRI = '5X15', _('Shahrisabz shahri')
    KOKDALA = '5X16', _('Ko‘kdala tumani')

    #NAVOIY
    ZARAFSHON = '6X1', _('Zarafshon shahri')
    KARMANA = '6X2', _('Karmana tumani')
    QIZILTEPA = '6X3', _('Qiziltepa tumani')
    KONIMEX = '6X4', _('Konimex tumani')
    NAVBAHOR = '6X5', _('Navbahor tumani')
    NAVOIY = '6X6', _('Navoiy shahri')
    NUROTA = '6X7', _('Nurota tumani')
    TOMDI = '6X8', _('Tomdi tumani')
    UCHQUDUQ = '6X9', _('Uchquduq tumani')
    XATIRCHI = '6X10', _('Xatirchi tumani')
    GOZGON = '6X11', _('G‘ozg‘on shahri')

    #NAMANGAN
    KOSONSOY = '7X1', _('Kosonsoy tumani')
    MINGBULOQ = '7X2', _('Mingbuloq tumani')
    NAMANGAN = '7X3', _('Namangan tumani')
    NAMANGAN_SHAHRI = '7X4', _('Namangan shahri')
    NORIN = '7X5', _('Norin tumani')
    POP = '7X6', _('Pop tumani')
    TORAQORGON = '7X7', _('To‘raqo‘rg‘on tumani')
    UYCHI = '7X8', _('Uychi tumani')
    UCHQORGON = '7X9', _('Uchqo‘rg‘on tumani')
    CHORTOQ = '7X10', _('Chortoq tumani')
    CHUST = '7X11', _('Chust tumani')
    YANGIQORGON = '7X12', _('Yangiqo‘rg‘on tumani')
    DAVLATOBOD = '7X13', _('Davlatobod tumani')

    #SAMARQAND
    BULUNGUR = '8X1', _('Bulung‘ur tumani')
    JOMBOY = '8X2', _('Jomboy tumani')
    ISHTIXON = '8X3', _('Ishtixon tumani')
    KATTAQORGON = '8X4', _('Kattaqo‘rg‘on tumani')
    KATTAQORGON_SHAHRI = '8X5', _('Kattaqo‘rg‘on shahri')
    QOSHRABOT = '8X6', _('Qo‘shrabot tumani')
    NARPAY = '8X7', _('Narpay tumani')
    NURABOD = '8X8', _('Nurabod tumani')
    OQDARYO = '8X9', _('Oqdaryo tumani')
    PAYARIQ = '8X10', _('Payariq tumani')
    PASTARGOM = '8X11', _('Pastarg‘om tumani')
    PAXTACHI = '8X12', _('Paxtachi tumani')
    SAMARQAND = '8X13', _('Samarqand tumani')
    SAMARQAND_SHAHRI = '8X14', _('Samarqand shahri')
    TOYLOQ = '8X15', _('Toyloq tumani')
    URGUT = '8X16', _('Urgut tumani')
    
    #SURXANDARYO
    ANGOR = '9X1', _('Angor tumani')
    BOYSUN = '9X2', _('Boysun tumani')
    DENOV = '9X3', _('Denov tumani')
    JARQORGON = '9X4', _('Jarqo‘rg‘on tumani')
    QIZIRIQ = '9X5', _('Qiziriq tumani')
    QOMQORGON = '9X6', _('Qo‘mqo‘rg‘on tumani')
    MUZRABOT = '9X7', _('Muzrabot tumani')
    OLTINSOY = '9X8', _('Oltinsoy tumani')
    SARIOSIYO = '9X9', _('Sariosiyo tumani')
    TERMIZ = '9X10', _('Termiz tumani')
    TERMIZ_SHAHRI = '9X11', _('Termiz shahri')
    UZUN = '9X12', _('Uzun tumani')
    SHEROBOD = '9X13', _('Sherobod tumani')
    SHORCHI = '9X14', _('Sho‘rchi tumani')
    BANDIXON = '9X15', _('Bandixon tumani')
    
    #SIRDARYO
    BOYOVUT = '10X1', _('Boyovut tumani')
    GULISTON = '10X2', _('Guliston tumani')
    GULISTON_SHAHRI = '10X3', _('Guliston shahri')
    MIRZAOBOD = '10X4', _('Mirzaobod tumani')
    OQOLTIN = '10X5', _('Oqoltin tumani')
    SAYXUNOBOD = '10X6', _('Sayxunobod tumani')
    SARDOBA = '10X7', _('Sardoba tumani')
    SIRDARYO = '10X8', _('Sirdaryo tumani')
    XAVOS = '10X9', _('Xavos tumani')
    SHIRIN = '10X10', _('Shirin shahri')
    YANGIYER = '10X11', _('Yangiyer shahri')
    
    #TOSHKENT
    ANGIREN = '11X1', _('Angiren shahri')
    BEKABOD = '11X2', _('Bekabod tumani')
    BEKABOD_SHAHRI = '11X3', _('Bekabod shahri')
    BOKA = '11X4', _('Bo‘ka tumani')
    BOSTONLIQ = '11X5', _('Bo‘stonliq tumani')
    ZANGIOTA = '11X6', _('Zangiota tumani')
    QIBRAY = '11X7', _('Qibray tumani')
    QUYICHIRCHIQ = '11X8', _('Quyichirchiq tumani')
    OQQORGON = '11X9', _('Oqqo‘rg‘on tumani')
    OLMALIQ = '11X10', _('Olmaliq shahri')
    OHANGARON = '11X11', _('Ohangaron tumani')
    PARKENT = '11X12', _('Parkent tumani')
    PISKENT = '11X13', _('Piskent tumani')
    ORTACHIRCHIQ = '11X14', _('O‘rtachirchiq tumani')
    CHINOZ = '11X15', _('Chinoz tumani')
    CHIRCHIQ = '11X16', _('Chirchiq shahri')
    YUQORICHIRCHIQ = '11X17', _('Yuqorichirchiq tumani')
    YANGIYOL = '11X18', _('Yangiyo‘l tumani')
    OHANGARON_SHAHRI = '11X19', _('Ohangaron shahri')
    YANGIYOL_SHAHRI = '11X20', _('Yangiyo‘l shahri')
    TOSHKENT = '11X21', _('Toshkent tumani')
    
    #FARGONA
    BESHARIQ = '12X1', _('Beshariq tumani')
    BOGDOD = '12X2', _('Bog‘dod tumani')
    BUVAYDA = '12X3', _('Buvayda tumani')
    DANGARA = '12X4', _('Dang‘ara tumani')
    YOZYOVON = '12X5', _('Yozyovon tumani')
    QUVA = '12X6', _('Quva tumani')
    QUVASOY = '12X7', _('Quvasoy shahri')
    QOQON = '12X8', _('Qo‘qon shahri')
    QOSHTEPA = '12X9', _('Qo‘shtepa tumani')
    MARGILON = '12X10', _('Marg‘ilon shahri')
    OLTIARIQ = '12X11', _('Oltiariq tumani')
    RISHTON = '12X12', _('Rishton tumani')
    SOX = '12X13', _('So‘x tumani')
    TOSHLOQ = '12X14', _('Toshloq tumani')
    UCHKOPRIK = '12X15', _('Uchko‘prik tumani')
    OZBEKISTON = '12X16', _('O‘zbekiston tumani')
    FARGONA = '12X17', _('Farg‘ona tumani')
    FARGONA_SHAHRI = '12X18', _('Farg‘ona shahri')
    FURQAT = '12X19', _('Furqat tumani')
    
    #XORAZM
    BOGOT = '13X1', _('Bog‘ot tumani')
    GURLAN = '13X2', _('Gurlan tumani')
    QOSHKOPIR = '13X3', _('Qo‘shko‘pir tumani')
    URGANCH = '13X4', _('Urganch tumani')
    URGANCH_SHAHRI = '13X5', _('Urganch shahri')
    XIVA = '13X6', _('Xiva tumani')
    XAZARASP = '13X7', _('Xazarasp tumani')
    XONQA = '13X8', _('Xonqa tumani')
    SHAVOT = '13X9', _('Shavot tumani')
    YANGIARIQ = '13X10', _('Yangiariq tumani')
    YANGIBOZOR = '13X11', _('Yangibozor tumani')
    XIVA_SHAHRI = '13X12', _('Xiva shahri')
    DOSTLIK = '13X13', _('Do‘stlik shahri')
    TUPROQQALA = '13X14', _('Tuproqqala tumani')

    #TOSHKENT_SHAHRI
    BEKTIMER = '14X1', _('Bektimer tumani')
    MIRZO = '14X2', _('Mirzo Ulug‘bek tumani')
    MIROBOD = '14X3', _('Mirobod tumani')
    OLMAZOR = '14X4', _('Olmazor tumani')
    SIRGALI = '14X5', _('Sirg‘ali tumani')
    UCHTEPA = '14X6', _('Uchtepa tumani')
    YASHNOBOD = '14X7', _('Yashnobod tumani')
    CHILONZOR = '14X8', _('Chilonzor tumani')
    SHAYXONTOHUR = '14X9', _('Shayxontohur tumani')
    YUNUSOBOD = '14X10', _('Yunusobod tumani')
    YAKKASAROY = '14X11', _('Yakkasaroy tumani')
    YANGIHAYOT = '14X12', _('Yangihayot tumani')