name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AksiyaMix_SSH_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.46.244.179 << 'EOF'
            cd /home/azureuser/aksiyamix
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            exit
          EOF
